travis:
  secure:
    BINSTAR_TOKEN: mIrQWfhFVFbT7q00HiU8fkTdX775FTTUb+0qUhuL+44TvvOijkuLOubjuuktHnLBnFhPHx0T1P2Uaf7pWwoJhsIw1urPsTICQ/2BnR4PLT3TwIoZKanKIB/4XaYEg6m6U4Q/a+mQcsKsbKIaWXEnHBWEdHsCtbdJPPMWvfznNix4OxoMFt4FvceokS6e906Z71HLBMIuPw79d3jq0fo0G2PunztYmaj8KTIfW6vdQWMHY2jhfJvj5uESklBpr/xzPbyWHSVNqDquOmYNfd7jERfRO2Q7q644lay1QkxOEjHNb3OnluIc5e8FkLDNI74RPsBiP8cxe/wFEMv33+2pvOgofKsbPsRHihk6WzOKbpOT8e3Rcr2xZ/nZi76ltaaIcT/3jhokjkZiQ5RYnNf2om7KTNdl8Y3RsK3QPKYmz2UGwKczrctGI/nxKCwN8WApif1dgApnUkj4DaxxeOfcBHIKVOCHpCkDrXt9rkldvbUD4HsMT/4I4ahU5aRGkCPuiVc0xmS0F6gZAuqnT81y2osfHDuTG0D1nAG7EAI4AXGvoHsltApt6HsBHJ5nfpmKFli2sLv7kT9wlC+hIG61Lp3l+9+gLnFZuNC/yqy5qh8c8kiOW3rGO88cr8Zg9CddAnM+jqcoS5wsTYtAP8hZFe78iFuPra/GQXakj2SS82c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
